"use client";

import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import favicon from "../public/favicon.ico";
import caricature from "../public/Caricature.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  console.log("Home component rendered");
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Karan Shah Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon} />
      </Head>

      <main className="bg-white dark:bg-gray-900 p-10 md:px-20 md:text-center lg:px-40">
        <section className="p-10">
          {/* min-h-screen */}
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-3xl">Karan Manishkumar Shah</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1G2h6qmQhscg2400SM1uvB1EMFzB_E4Wr/view?usp=sharing"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 dark:text-teal-400 text-teal-600 font-medium md:text-6xl">
              Karan Shah
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer | Backend & Cloud Enthusiast | Problem-Solver
            </h3>
            <p className="text-md py-4 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              I’m a Software Engineer with expertise in{" "}
              <strong>
                backend development, distributed systems, and cloud computing
              </strong>
              . My proficiency in{" "}
              <strong>
                Python, JavaScript, C#, and cloud-native architectures
              </strong>{" "}
              allows me to design{" "}
              <strong>scalable, high-performance applications</strong> that
              solve complex challenges.
            </p>
            <p className="text-md py-4 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              I excel in <strong>high-impact environments</strong>, focusing on
              optimizing system efficiency, building{" "}
              <strong>fault-tolerant architectures</strong>, and creating{" "}
              <strong>robust, API-driven solutions</strong>. My background in{" "}
              <strong>AV systems engineering</strong> provides me with a unique
              perspective that blends hardware integration with scalable
              software solutions.
            </p>
            <p className="text-md py-4 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              I am passionate about{" "}
              <strong>
                building backend services, optimizing database performance, and
                ensuring system reliability
              </strong>
              . Whether it is{" "}
              <strong>
                deploying microservices, enhancing cloud infrastructure, or
                improving DevOps workflows
              </strong>
              , I am dedicated to driving technical excellence.
            </p>
            <p className="text-md py-4 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              Let’s connect to explore how I can contribute to your team! 🚀
            </p>
            <p className="text-md py-3 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              <strong>Tech Stack:</strong> Python, JavaScript, C#, ASP.NET,
              Flask, Node.js, Docker, AWS, PostgreSQL, MongoDB, Redis
            </p>
            <p className="text-md py-3 leading-8 dark:text-gray-200 text-gray-700 md:text-xl max-w-large mx-auto">
              <strong>Key Strengths:</strong> Backend Development, API Design,
              Cloud Computing, Performance Optimization, Distributed Systems,
              Database Management
            </p>
          </div>
          <div className="text-6xl flex justify-center py-3 text-gray-500 dark:text-gray-400">
            <a
              href="https://github.com/shahkaran281"
              target="_blank"
              rel="noreferrer"
              className="hover:text-blue-600"
            >
              <h3 className="icon">
                <AiFillGithub />
              </h3>
            </a>
            <a
              href="https://www.linkedin.com/in/karan---shah/"
              target="_blank"
              rel="noreferrer"
              className="hover:text-sky-600"
            >
              <h3 className="icon">
                <AiFillLinkedin />
              </h3>
            </a>
          </div>
          {/* <div className="relative bg-gradient-to-r from-cyan-500 to-teal-500 mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={caricature}
              alt="Karan Shah Caricature"
              fill
              priority
              sizes="(max-width: 768px) 100vw, 50vw"
              style={{ objectFit: "contain" }}
            />
          </div> */}
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Core Competencies</h3>
            <div className="flex justify-center py-5 leading-8 text-gray-700 dark:text-gray-200">
              <ul className="list-disc text-left ml-5 mr-10">
                <li>
                  Full-stack web application development using MERN stack and
                  ASP.NET Core
                </li>
                <li>Front-end development with Angular and React</li>
                <li>RESTful API design, implementation, and integration</li>
              </ul>
              <ul className="list-disc text-left ml-5">
                <li>
                  Cloud-based application deployment and management (AWS, Google
                  Cloud Platform)
                </li>
                <li>
                  Mobile-first and responsive web design with cross-platform
                  compatibility
                </li>
                <li>Database management and optimization (SQL and NoSQL)</li>
              </ul>
            </div>
          </div>

          <div className="lg:flex flex-wrap gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-5 bg-white dark:bg-gray-800 w-full lg:w-[calc(50%-20px)]">
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-900 dark:text-gray-100">
                Mobile-first Event Information System
              </h3>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Engineered a responsive, mobile-first website that enhanced
                event discovery and sharing through dynamic search, map
                integration, and social media features, showcasing skills in
                full-stack web development and API integration.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Implemented user-centric design principles, prioritizing
                intuitive navigation and seamless interaction, demonstrating
                proficiency in mobile-first and responsive design.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Integrated advanced features such as autocomplete functionality
                and efficient data storage for improved user experience,
                highlighting expertise in performance optimization and user
                interface design.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Successfully deployed and managed the project on a cloud
                platform, demonstrating proficiency in cloud technologies and
                project management.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-5 bg-white dark:bg-gray-800 w-full lg:w-[calc(50%-20px)]">
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-900 dark:text-gray-100">
                Event Booking System
              </h3>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Created a dynamic website that leveraged a third-party API to
                present comprehensive event information in an organized,
                user-friendly format, exhibiting skills in API integration and
                data management.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Developed interactive web pages to enhance user engagement and
                streamline content delivery, showcasing abilities in front-end
                development and user experience design.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Utilized cloud deployment strategies to ensure scalability and
                accessibility of the application, demonstrating knowledge of
                cloud technologies and system architecture.
              </p>{" "}
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-5 bg-white dark:bg-gray-800 w-full lg:w-[calc(50%-20px)]">
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-900 dark:text-gray-100">
                Mortgage-Backed Securities Prepayment Prediction System{" "}
              </h3>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Led a team in developing a predictive model for customer
                prepayment likelihood, resulting in a 14% performance
                improvement, showcasing leadership skills and expertise in data
                analysis and predictive modeling.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Applied advanced statistical and machine learning techniques to
                achieve 95.8% accuracy in predictions, demonstrating proficiency
                in machine learning and statistical analysis.
              </p>
              <p className="py-2 text-justify text-gray-800 dark:text-gray-200">
                Designed and implemented a user interface with a REST API,
                allowing users to interact with and test the deployed model,
                highlighting skills in full-stack development and API design.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
