"use client";

import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import favicon from "../public/favicon.ico";
import caricature from "../public/Caricature.png";
export default function Home() {
  console.log("Home component rendered"); // Debug log
  return (
    <div>
      <Head>
        <title>Karan Shah Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon} />
      </Head>

      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-3xl">Karan Manishkumar Shah</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Karan Shah
            </h2>
            <h3 className="text-2xl py-2">Software Engineer and AV Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-700">
              Versatile full-stack developer skilled in Python and JavaScript,
              specializing in React and Angular frameworks. Creates responsive,
              efficient web applications with a focus on user experience.
              Leverages 2 years of AV engineering background to bring unique
              problem-solving skills to software projects. Combines front-end
              expertise with back-end knowledge to deliver scalable solutions.
              Thrives in collaborative environments, driving innovation through
              a blend of software development and practical AV experience.
            </p>
          </div>
          <div className="text-5xl flex justify-center py-3 text-gray-500">
            <AiFillLinkedin />
          </div>
          <div className="relative bg-gradient-to-r from-cyan-500 to-teal-500 mx-auto to rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image
              src={caricature}
              alt="Karan Shah Caricature"
              layout="fill"
              objectFit="contain"
              priority={true}
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Core Competencies</h3>
            <div className="flex py-5 leading-8 text-gray-700">
              <ul className="list-disc ml-5 mr-10">
                <li>
                  Full-stack web application development using MERN stack and
                  ASP.NET Core
                </li>
                <li>Front-end development with Angular and React</li>
                <li>RESTful API design, implementation, and integration</li>
              </ul>
              <ul className="list-disc ml-5">
                <li>
                  Cloud-based application deployment and management (AWS, Google
                  Cloud Platform)
                </li>
                <li>
                  Mobile-first and responsive web design with cross-platform
                  compatibility
                </li>
                <li>Database management and optimization (SQL and NoSQL)</li>
              </ul>
            </div>
          </div>
          <div></div>
        </section>
      </main>
    </div>
  );
}
